
version: "3.9"

services:

  backend: 
    image: 'clowder/clowder-fastapi:${TAG:-latest}'
    build:
      # export GH_ACCESS_TOKEN=your-personal=access-token
      context: https://${GH_ACCESS_TOKEN}:@github.com/clowder-framework/clowder2-fastapi
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MINIO_SERVER_URL: minio:9000
    ports:
      - "8888:80"
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  minio:
    image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: clowder
      MINIO_ROOT_PASSWORD: clowdersecret
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio:
  mongo:
