
version: "3.9"

services:


  react:
    container_name: "clowder2-frontend"
    image: "clowder/clowder2-frontend"
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      CLOWDER_REMOTE_HOSTNAME: ${CLOWDER_REMOTE_HOSTNAME}


